### ISSUE TITLE
Kickstarter change breaks reward name extraction

### ISSUE THREAD

**Issue by thetamind** [pointybeard/kickstarter-export-parser#4]
Kickstarter appears to have changed the file names in the backer report zip. They no longer include the `Kickstarter Backer Report` prefix.

Before:
`Kickstarter Backer Report - No Reward - Jan 01 07am.csv`
After:
`No Reward - Jan 01 07am.csv`

`BackerArchive->rewardNameFromFileName` should be updated to account for both cases.

**Comment by pointybeard** [comment]
Thanks for the heads up. I will grab a new export from KS and update the code accordingly. I will also look at making it a little more robust to handle future file name changes.

**Comment by pointybeard** [comment]
After some thought, I think it's best to not mess with the filename at all and rather present the full filename during import. Going to push that change for next update.
